### ISSUE TITLE
为什么很多东西都找不到本体

### ISSUE THREAD

**Issue by linonetwo** [taurenshaman/semantic-web#2]
例如我今天想在太微里记录一下深睡时长，都记不了。

ChatGPT 对于这类问题也只会胡说八道

**Comment by linonetwo** [comment]
# ChatGPT Conversation

**Human:**
2 / 2
有哪些和睡眠相关的语义网 Ontology，其中哪些涉及到了深度睡眠时长？

***

**Assistant:**

在睡眠领域，有一些与睡眠相关的语义网本体（ontology），它们有助于描述和组织与睡眠相关的知识。以下是一些与睡眠相关的语义网本体，其中一些涉及深度睡眠时长：

1. 
Sleep Ontology (SleepOntology): SleepOntology 是一个用于描述睡眠相关概念和关系的本体。它包括了与睡眠周期、睡眠阶段、睡眠障碍等相关的术语和属性。该本体可以用于研究和分析睡眠数据以及睡眠相关的领域。

2. 
Sleep Disorders Ontology (SDO): Sleep Disorders Ontology 是一个专注于睡眠障碍的本体。它包括了多种睡眠障碍的分类、症状、诊断和治疗方法等信息。该本体可以帮助医生和研究人员更好地理解和处理睡眠障碍。

3. 
National Sleep Research Resource Ontology (NSRR Ontology): NSRR Ontology 是一个与睡眠研究相关的本体。它提供了描述睡眠研究数据集、实验设计和测量工具等信息的术语和关系。该本体可以用于共享和整合睡眠研究数据，促进睡眠研究的协作和发展。



上述的语义网本体中，并不是所有都明确涉及深度睡眠时长。深度睡眠时长通常是通过睡眠监测设备、脑电图（EEG）等工具测量得到的。因此，在语义网本体中，对于深度睡眠时长的描述可能会涉及到与睡眠阶段、睡眠评估或睡眠质量等相关的术语和属性。使用这些本体可以帮助整理和分析与睡眠相关的数据和知识。


***

**Human:**
其中描述深度睡眠时长的字段是什么？给出相应 uri

***

**Assistant:**

根据我当前的知识，没有特定的语义网本体字段专门描述深度睡眠时长。然而，可以使用一些通用的字段或属性来描述睡眠阶段和睡眠时长，其中包括深度睡眠。以下是一些可能用于描述睡眠时长和深度睡眠的通用字段：

1. 
"duration"（时长）：描述睡眠阶段或特定的睡眠状态的时长，包括深度睡眠时长。

2. 
"sleepStageDuration"（睡眠阶段时长）：用于描述各个睡眠阶段（如深度睡眠、浅睡眠、快速动眼期等）的时长。



请注意，这些字段可能在不同的语义网本体中有不同的命名或URI。具体使用哪个字段取决于所选的本体或数据模型。


***

**Human:**
2 / 2
前述睡眠相关本体主要描述了什么，给出几个 RDF 或 JSON-LD 使用案例及其描述的内容的中文翻译

***

**Assistant:**

以下是一些针对睡眠相关本体的 RDF 或 JSON-LD 使用案例及其内容的中文翻译：

1. Sleep Ontology (SleepOntology):
RDF 示例：


```
<http://example.com/sleepdata/12345> rdf:type <http://example.com/ontology/SleepRecord> .
<http://example.com/sleepdata/12345> <http://example.com/ontology/sleepDuration> "360" .
<http://example.com/sleepdata/12345> <http://example.com/ontology/sleepStage> <http://example.com/ontology/DeepSleep> .

```

翻译：

```
<http://example.com/sleepdata/12345> 是一个 SleepRecord 类型的记录。
<http://example.com/sleepdata/12345> 的 sleepDuration 是 "360"。
<http://example.com/sleepdata/12345> 的 sleepStage 是 DeepSleep。

```
<ol start="2">Sleep Disorders Ontology (SDO):
JSON-LD 示例：</li></ol>
```
{
  "@context": {
    "sdo": "http://example.com/ontology/sdo#",
    "sd": "http://example.com/data/sleepdisorders#"
  },
  "@id": "sd:patient1",
  "@type": "sdo:Patient",
  "sdo:hasSleepDisorder": {
    "@id": "sd:insomnia",
    "@type": "sdo:SleepDisorder",
    "sdo:symptoms": "Difficulty falling asleep"
  }
}

```

翻译：

```
{
  "@context": {
    "sdo": "http://example.com/ontology/sdo#",
    "sd": "http://example.com/data/sleepdisorders#"
  },
  "@id": "sd:patient1",
  "@type": "sdo:Patient",
  "sdo:hasSleepDisorder": {
    "@id": "sd:insomnia",
    "@type": "sdo:SleepDisorder",
    "sdo:symptoms": "入睡困难"
  }
}

```
<ol start="3">National Sleep Research Resource Ontology (NSRR Ontology):
RDF 示例：</li></ol>
```
<http://example.com/nsrr/data/98765> rdf:type <http://example.com/ontology/SleepStudy> .
<http://example.com/nsrr/data/98765> <http://example.com/ontology/hasMeasurement> <http://example.com/nsrr/data/98765/measurements> .
<http://example.com/nsrr/data/98765/measurements> rdf:type <http://example.com/ontology/SleepMeasurement> .
<http://example.com/nsrr/data/98765/measurements> <http://example.com/ontology/recordedDuration> "420" .

```

翻译：

```
<http://example.com/nsrr/data/98765> 是一个 SleepStudy 类型的研究。
<http://example.com/nsrr/data/98765> 有一个 Measurement，它的 URI 是 <http://example.com/nsrr/data/98765/measurements>。
<http://example.com/nsrr/data/98765/measurements> 是一个 SleepMeasurement 类型的测量。
<http://example.com/nsrr/data/98765/measurements> 的 recordedDuration 是 "420"。

```

这些示例提供了对睡眠相关本体中的数据和关系进行描述的基本语法和结构。实际应用中，具体的本体和数据模型可能有不同的 URI 和属性命名。您可以根据具体的本体和数据模型进行调整。


***

Exported on 2023年6月1日 下午7:12.

**Comment by taurenshaman** [comment]
我当时搜集的时候，也没有发现相关的本体。

chat-gpt很给力啊，根据它提供的信息，我找到了：
* [NSRR](https://sleepdata.org/) ：它的datasets里面，每个数据集都有[Variables](https://sleepdata.org/datasets/chat/variables)，大概可以提取成本体？
* [SDO: Sleep Disorders Ontology](https://bioportal.bioontology.org/ontologies/SDO)： 最后一次更新是2015年
* [Ontogeny of Sleep](https://psychology.uiowa.edu/sites/psychology.uiowa.edu/files/groups/blumberg/files/Reprints/Blumberg%20Encylopedia%202013.pdf)
* [EEG-Based Automatic Sleep Staging Using Ontology and Weighting Feature Analysis](https://www.hindawi.com/journals/cmmm/2018/6534041/)

**Comment by linonetwo** [comment]
好吧，不过我主要是看有没有「深睡时长」这个字段，我目前就是用自定义的了，反正先用起来再说
